version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0

workflows:
  build:
    jobs:
      - cypress/run:
          executor: cypress/base-14
          yarn: true
          store_artifacts: true
          post-steps:
            - store_test_results:
                path: reports
