version: '2.1'
orbs:
  node: circleci/node@5.0.1
jobs:
  test:
    executor:
      name: node/default
      tag: '16.14.2'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test
      - store_artifacts:
          path: /reports
      - store_test_results:
          path: reports

workflows:
  test_my_app:
    jobs:
      - test
